stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/algodesreseaux

build_3:
  stage: build
  script:
    - cd 3-bit-alterne
    - make
  artifacts:
    paths:
      - 3-bit-alterne/sender-udp
      - 3-bit-alterne/receiver-udp
      - 3-bit-alterne/medium

# run tests using the binary build before
test_3:
  stage: test
  needs: [build_3]
  script:
  - |
    echo "starting test"
    cd 3-bit-alterne
    make test
