stages:
  - build
  - test

image: registry.app.unistra.fr/montavont/img-docker/algodesreseaux

build_1.2:
  stage: build
  script:
    - cd 1-udp/1.2-recepteur
    - make
  artifacts:
    paths:
      - 1-udp/1.2-recepteur/receiver-udp

# run tests using the binary build before
test_1.2:
  stage: test
  needs: [build_1.2]
  script:
  - |
    echo "starting test"
    cd 1-udp/1.2-recepteur
    make test
